### ISSUE TITLE
Page not found issue

### ISSUE THREAD

**Issue by jpslootmans** [DoctorMcKay/chromium-tesla-token-generator#1]
Worked fine until a couple of days ago. Now I get a "Page not found" error every time.

**Comment by DoctorMcKay** [comment]
Still works for me. Please give browser and extension version, and the URL of the page that says not found.

**Comment by jpslootmans** [comment]
Hello,

browser is Chrome on PC, but after reinstalling the extension, everything
is working fine again.
Sorry for the trouble,

thanks,
JP

Op zo 14 aug. 2022 om 06:15 schreef DoctorMcKay ***@***.***>:

**Comment by DoctorMcKay** [comment]
Glad to hear it.
