### ISSUE TITLE
Not working in combination with MFA

### ISSUE THREAD

**Issue by jcjveraa** [DoctorMcKay/chromium-tesla-token-generator#2]
Hi there, I just tried your plugin twice: once without MFA (TOTP) and once with, and the fist time it worked and the second time it didn't. It says 'verification succes' (or something like that in Dutch) and then a page not found error page. 

Any clues? I might try to figure it out later myself.

**Comment by DoctorMcKay** [comment]
I just tried it and had the opposite experience to you; it failed the first time and worked the second (and subsequent tries). All with MFA. I'll keep trying to reproduce this again.

**Comment by jcjveraa** [comment]
Ah interesting. Meanwhile I've been helped with the iPhone app https://github.com/TeslaBuds/AuthAppForTesl. This worked first time, but of course in a very different browser.FYI I used the Edge plugin.Good luck bughunting :)Verstuurd vanaf mijn iPhoneOp 4 okt. 2023 om 08:10 heeft DoctorMcKay ***@***.***> het volgende geschreven:﻿
I just tried it and had the opposite experience to you; it failed the first time and worked the second (and subsequent tries). All with MFA. I'll keep trying to reproduce this again.

**Comment by DoctorMcKay** [comment]
The browser was terminating the background script after a period of inactivity, which caused loss of the OAuth code verifier. Fixed by persisting the verifier into the browser's extension session storage rather than a global variable in the background script.

**Comment by jcjveraa** [comment]
Great! Makes sense that this pops up only now as these energy saving features are fairly new.Verstuurd vanaf mijn iPhoneOp 12 okt. 2023 om 07:43 heeft DoctorMcKay ***@***.***> het volgende geschreven:﻿
The browser was terminating the background script after a period of inactivity, which caused loss of the OAuth code verifier. Fixed by persisting the verifier into the browser's extension session storage rather than a global variable in the background script.

**Comment by DoctorMcKay** [comment]
Indeed. Also makes sense why it would be associated with MFA, since getting an MFA code is likely to delay you long enough for the inactivity limit to kick in.
